### ISSUE TITLE
Update for newer parts

### ISSUE THREAD

**Issue by arjanvillon** [docyx/pc-part-dataset#1]
Hi! This is an amazing app. I would just like to suggest to do a new update again for the parts list under the data folder. Thank you very much for this.

**Comment by docyx** [comment]
Unfortunately PCPP have improved their countermeasures for bots / scrapers, which makes me unable to update the data. I keep getting 503s even with a VPN enabled.

I plan to rewrite in Selenium / maybe TypeScript + Puppeteer to circumvent this. Give me a few days to a week and I'll get this back to where it was (:

**Comment by arjanvillon** [comment]
Thank you very much. Can't wait for this new app. I'll follow you so I can see if I can help someday on your work :)

**Comment by docyx** [comment]
@arjanvillon @Ricebowl23 @burakdmir Apologies for the delay - data has been updated (:
