### ISSUE TITLE
Will be any online api available?

### ISSUE THREAD

**Issue by WilczekCK** [docyx/pc-part-dataset#2]
As the topic says.
I'm currently using the local JSON file, but I think it could be a really good api if it will be updated and available for public.

Thanks

**Comment by WilczekCK** [comment]
Keep in touch if you need some help, surely it will be released faster :)

**Comment by docyx** [comment]
Node. I'll get a basic prototype going and let you know when it's up on GH. Thanks

**Comment by docyx** [comment]
Update: unfortunately I haven't had the time to get started on this. If you need something sooner than, say, within the next month or two, please let me know. Otherwise it'll get done... at some point.

Sorry!

**Comment by WilczekCK** [comment]
No problem, I'm using the JSON file right now, so its not necessary, but would be helpful 😁

**Comment by WalterClementsJr** [comment]
Sadly, it's against [PCPartPicker's TOS](https://pcpartpicker.com/tos) (in the Access section).

**Comment by docyx** [comment]
> Sadly, it's against [PCPartPicker's TOS](https://pcpartpicker.com/tos) (in the Access section).

Not sure why this is being brought up. It's publicly available data that is being synchronously scraped. Worst that can happen is an IP ban. In that case, VPN :)

**Comment by docyx** [comment]
@PierrunoYT just uploaded https://github.com/docyx/pc-part-dataset/tree/main/data

**Comment by docyx** [comment]
No plans for an API. Closing.
