### ISSUE TITLE
Out of range list's index

### ISSUE THREAD

**Issue by not-NEKO** [docyx/pc-part-dataset#3]
Everything is installed, maybe it's my fault but i don't know where i'm wrong.
**INPUT:**
```bash
python -m pipenv run python scripts/scrape.py
```
**OUTPUT:**
```bash
Traceback (most recent call last):
  File "scripts/scrape.py", line 137, in <module>
    scrape(endpoint, session=session)
  File "scripts/scrape.py", line 70, in scrape
    max_pages = int(h.find(".pagination > li")[-1].text)
IndexError: list index out of range
```

**Comment by docyx** [comment]
Hey, sorry for the late reply -- PCPartPicker has implemented a captcha that makes scraping really difficult, and kind of breaks this whole script, which is why the data hasn't been updated in nearly 2 years.

I haven't had time to work on a new scraper but it'll come at some point. Sorry!

**Comment by docyx** [comment]
data has been updated as of #5, everything should be in working order now :)
