### ISSUE TITLE
fix boost_clock serialization map to match new page layout

### ISSUE THREAD

**Issue by guipace** [docyx/pc-part-dataset#9]
The key on this line needs to be updated from `Performance Boost Clock` to `Performance Core Boost Clock`; PCPP changed their column heading.

I tried creating a PR for this, but doesn't seem like it's possible to contribute to this repo.

https://github.com/docyx/pc-part-dataset/blob/53cd6c1b890679a065e0cd7cd2a13b51ba4ff3d4/src/serialization-map.json#L5C32-L5C43

<img width="782" alt="image" src="https://github.com/docyx/pc-part-dataset/assets/63423828/1bc4082a-7451-4a70-a358-8438bf01fd82">

**Comment by docyx** [comment]
4908df9e63fc98bafea4d1465447bfd05466fb47 fixes this.

> I tried creating a PR for this, but doesn't seem like it's possible to contribute to this repo.

Can you elaborate on this? Did you get an error or something?

**Comment by guipace** [comment]
I got the following error trying to push a branch:

```
git push --set-upstream origin gp/fix_serialization_map_cpu
remote: Permission to docyx/pc-part-dataset.git denied to guipace.
fatal: unable to access 'https://github.com/docyx/pc-part-dataset.git/': The requested URL returned error: 403
```

**Comment by docyx** [comment]
Try forking?

**Comment by guipace** [comment]
The intent was to collaborate on this repo instead of forking and maintaining it separately.

**Comment by docyx** [comment]
This is what I mean:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

I can't just let anyone push a change without approval. You can fork and then submit a PR through it.
